### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-security-intro#76]
- [x] Commands under `Running the Tests` are not showing up correctly with [role="command"]

**Comment by Erikkre** [comment]
### Configuring the user registry
-readme.adoc line 156 dave's hotspot should be pointing at line 27 not 277

### Adding authentication and authorization
- [ ]  @HttpConstraint annotation rolesAllowed are not properly positioned hotspots

### Testing the application
- [ ] admin and user roles should not be hotspots in the SecurityTest.java file
- [ ]  testAuthenticationFail(), testAuthorizationFail(), testAuthorizationForAdmin() and testAuthorizationForUser() hotspots should be properly positioned

### Checklist for Review
**Through the browser:**
- [x] Read over guide and run through all commands (copy and paste using browser etc..)
- [x] Test the actual application (use it, hit endpoints, etc.)
- [x] No files in the middle panel (guide section)
- [x] Appropriate files are being displayed on the right hand side at the right time
- [x] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [x] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [x] All code commands are highlighting the right code
- [x] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present
- [x] Any links are hyperlinks with the webpage title not the URL
- [x] Feature versions should not be included in the guide
**In the README.adoc:**
- [x] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [x] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [x] Failsafe plugin and Surefire plugin updates if applicable
- [x] Parent POM update
    - [x] start directory
    - [x] finish directory
- [x] Files are formatted correctly
- [x] .travis.yaml file is updated accordingly

**Review**
- readme.adoc has no guide attribution at the end of the doc

**Comment by Rachelwrq** [comment]
### Getting Started
#### Try what you’ll build
- [ ] the url doesn't need to be in backticks anymore

### Adding authentication and authorization
- [ ] The action arrow highlights the whole file instead of the class.
- [ ] `@FormAuthenticationMechanismDefinition` hotspot needs to highlight one more line
- [ ] the `HomeServlet` hotspot in third last paragraph is off by one line
- [ ] last paragraph `<security-constraint>` element needs to be changed to `<security-constraint/>`

### Configuring the user registry
- [ ] the `server.xml` and `<include>` hotspots are off by one line.
- [ ] xml elements need to be changed from <xxx> to <xxx/>

### Building and running the application
- [ ] the url link doesn't need to be in backticks anymore

### Testing the application
- [ ] the entire file is highlighted instead of just the class in the action arrow
- [ ] Wrote `[role="code_command"]` instead of `[role='command']`, that might be the reason why the role command is not showing up correctly

### In the End
- [ ] End with "in Open Liberty" in the first sentence under "Nice work! You did it!"

**Comment by Rachelwrq** [comment]
### Checklist for Post-Review
**Through the browser:**
- [ ] Read through guide, making sure that the flow of the guide is good
- [ ] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [ ] Run Acrolinx

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
